### PR TITLE
Restructured docs

### PR DESCRIPTION
**Pull request by MattBuckley-TfN**
Describe Changes
---

Restructured the sphinx docs to follow the structure set out in caf.toolkit, some sections still need filling out and have TODO comments.

Task Checklist
----
- [x] Have unittests been added (testing individual functions and their edge cases) - NA
- [x] Have integration tests been added (if applicable, to test modules of functionality) - NA
- [x] Have new dependencies been added? - Yes
  - [x] Have they been added to either `requirements.txt` or `requirements_dev.txt`. - Yes to docs
- [x] Have any new features been properly integrated with the API (CLI and GUI)? - NA

----
📚 Documentation preview 📚: https://cafspace--41.org.readthedocs.build/en/41/

### CODE REVIEW

**Comment by MattBuckley-TfN** [comment]
Readthedocs failed due to timeout or memory consumption, this is slow because we have docs enabled for imports so that we can pickup aliases correctly but caf.space has alot of functions / classes imported so we may need to turn it off until they've been removed

**Comment by isaac-tfn** [comment]
Can't tell where all the TODOs are coming from, but : 

- there is a GUI and CLI and these are both documented,
-  suggested alias is cs, I don't know where that should be added, 
- I don't remember if @Kieran-Fishwick-TfN has pipx'ed space

**Comment by MattBuckley-TfN** [comment]
> Can't tell where all the TODOs are coming from, but :
> 
> * there is a GUI and CLI and these are both documented,
> * suggested alias is cs, I don't know where that should be added,
> * I don't remember if @Kieran-Fishwick-TfN has pipx'ed space

Pipx does work for space and other 2 are done

**Comment by MattBuckley-TfN** [comment]
Fixed the pylint positional arguments errors.

In `weighted_funcs.get_weighted_translation` I set `point_handling` and `point_tolerance` have default values  (False and 1) to make calling it simpler, @isaac-tfn are you happy with this?

https://github.com/Transport-for-the-North/caf.space/blob/c1082bf2173b5d3a36e6e2cc09d24eff1905c03d/src/caf/space/weighted_funcs.py#L190-L200

**Review by isaac-tfn — APPROVED** [review]
All looks good to me!

**Pull request merged**
